name: Lint

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    name: Check format

    container:
      image: ghcr.io/caphosra/haskell:latest
      options: --user root

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install fourmolu
        run: |
          sudo stack install fourmolu

      - name: Check sources in src
        run: |
          sudo fourmolu --mode check src

      - name: Check sources in app
        run: |
          sudo fourmolu --mode check app
